name: Deploy to Prachesta server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: scp to host as only html files
        run: |
          sudo apt-get install sshpass -y
          sshpass -p ${{ secrets.SERVER_PASSWORD }} scp -r . root@119.18.55.86:/var/www/html/git_hub_test/
