name: Deploy to Prachesta server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: scp to host as only html files
        run:
          ## sudo apt-get install sshpass -y
          sshpass -p ${{ secrets.PRACHESTA_SERVER_PASSWORD }} scp -r . ${{ secrets.PRACHESTA_USER}}@${{ secrets.PRACHESTA_IP }}:/var/www/html/git_hub_test/
        env:
          SSHPASS: ${{ secrets.PRACHESTA_SERVER_PASSWORD }}
